Add guiding details
school-brainhack/school-brainhack.readthedocs.org pull request #2
Opened 2023-03-08 00:48 UTC by complexbrains

2023-03-08 00:51 UTC, complexbrains commented
I would appreciate if you could review the current additions, but i will continue on updating the docs.

2023-03-08 20:44 UTC, clarkenj commented on docs/source/INSTRUCTORS.md
> +
shall we add a line like '- In the lead up to the school contribute to updating and adding new modules (optional)'?

2023-03-08 20:45 UTC, clarkenj commented on docs/source/INSTRUCTORS.md
> +### How is an instructor associated with students?
I don't think this section is necessary

2023-03-08 21:13 UTC, clarkenj requested changes
suggested comments on INSTRUCTORS.md. Apologies for some reason I could not suggest edits directly? Other files look great.

2023-03-08 21:13 UTC, clarkenj commented on docs/source/INSTRUCTORS.md
> +They are expected to but do not have to. Each hub will primarily be responsible for answering and helping its students. However, resolving some queries raised in the Discord server might address your
suggest removing the first sentence, it's confusing.

2023-03-08 21:13 UTC, clarkenj commented on docs/source/INSTRUCTORS.md
> +For tracking the progress with students' completion of the module assignments, the local hub organizers that you are affiliated with will provide a means, mostly a shared sheet with the students' nam
suggest replacing final sentence with something like "Students are asked to complete exercises for each module and share their progress with instructors, so that they can be marked as complete."

2023-03-08 21:13 UTC, clarkenj commented on docs/source/INSTRUCTORS.md
> +For the project improvements and assignments, meeting with the students 2 times a day will give you likely observations regarding how a student is progressing with their needs and executions.
suggest replacing with "For project progress, regular meetings with students should give you a good idea of how they are doing."

2023-03-08 21:13 UTC, clarkenj commented on docs/source/INSTRUCTORS.md
> +Please remember you are there to provide means for students to progress rather than tackling the question together. You are not expected to boggle down the code or execute a task for them, or not to
this is a bit repetitive of line 65. Suggest editing both together in one section, rephrasing or omitting one part

2023-03-08 21:13 UTC, clarkenj commented on docs/source/INSTRUCTORS.md
> +### What should I do if a student needs to complete module assignments?
edit: '_struggles_ to complete module assignments'

2023-03-08 21:13 UTC, clarkenj commented on docs/source/INSTRUCTORS.md
> +Similar to project executions, sometimes students might struggle with finishing the modules and the assignments due to technical struggles or time concerns because of other commitments they have.
this is unnecessary

2023-03-08 21:13 UTC, clarkenj commented on docs/source/INSTRUCTORS.md
> +Please remind yourself that strict requirements are especially expected for the students who take the course as a credited course.
rephrase as something like 'Students who undertake the school as a credited course must meet requirements of the school.'

2023-03-08 21:13 UTC, clarkenj commented on docs/source/INSTRUCTORS.md
> +### What should I do if a student claims they are already proficient in some modules and would like to be excluded from finishing the module issued as those modules are completed?
suggested edit "What should I do if a student asks to be excluded from completing a module, due to already being proficient in the material?"

2023-03-08 21:13 UTC, clarkenj commented on docs/source/INSTRUCTORS.md
> +However, please remember to keep the engagement and requests on kind terms rather than an obligatory ones.
I don't know if it makes sense to have this here, we could just have a general line about communication with students? Also 'obligatory terms' is not super clear

2023-03-09 00:33 UTC, complexbrains commented on docs/source/INSTRUCTORS.md
> +
Agreed.

2023-03-09 13:06 UTC, clarkenj approved these changes
LGTM!

2023-03-09 19:04 UTC, merged